export const state = () => ({
  GelenDiller: null,
  TurkishLanguage: [{
    "id": "1",
    "HeaderProfilAdi": "Profil",
    "HeaderProfilNesneDeposuAdi": "Nesne Deposu",
    "HeaderProfilYonetim": "Yönetim",
    "ZorunluAlanlarModalUstAlanIndirim": "İndirim",
    "ZorunluAlanlarModalUstAlanOrjinalFiyat": "Orjinal Fiyat",
    "ZorunluAlanlarModalUstAlanKazanc": "Kazanç",
    "ZorunluAlanlarModalUstAlanKostumSureUcreti": "Kostum Süre Ücreti",
    "HeaderEjderhaParasi": "EP",
    "ZorunluAlanlarModalUyariBasligi": "Lütfen Aşağidaki Alanlari Doldururken Dikkat Ediniz.!!!",
    "ZorunluAlanlarItemNereyeGonderilsinSelect": "Item Nereye Gönderilecek",
    "ZorunluAlanlarItemAdetBaslikSelect": "İtem Adedini Giriniz",
    "ZorunluAlanlarEfsunAktifSwitch": "Efsun Sistemi Aktif",
    "ZorunluAlanlarEfsunDeaktifSwitch": "Efsun Sistemi Deaktif",
    "ZorunluAlanlarTasAktifSwitch": "Taş Sistemi Aktif",
    "ZorunluAlanlarTasDeaktifSwitch": "Taş Sistemi Deaktif",
    "ZorunluAlanlarDikeyTabMenuBaslik": "Dinamik Özellikler Menusu",
    "ZorunluAlanlarDikeyTabEfsunText": "Efsun",
    "ZorunluAlanlarDikeyTabTasText": "Taş",
    "ZorunluAlanlarDikeyTabZamanText": "Zaman",
    "ZorunluAlanlarDikeyTabBilgiText": "Bilgi",
    "ZorunluAlanlarBirinciEfsunSecimiSelect": "1.Efsun Değeri",
    "ZorunluAlanlarIkinciEfsunSecimiSelect": "2.Efsun Değeri",
    "ZorunluAlanlarUcuncuEfsunSecimiSelect": "3.Efsun Değeri",
    "ZorunluAlanlarDorduncuEfsunSecimiSelect": "4.Efsun Değeri",
    "ZorunluAlanlarBesinciEfsunSecimiSelect": "5.Efsun Değeri",
    "ZorunluAlanlarAltinciEfsunSecimiSelect": "6.Efsun Değeri",
    "ZorunluAlanlarYedinciEfsunSecimiSelect": "7.Efsun Değeri",
    "ZorunluAlanlarFullOranAlani": "Oran",
    "ZorunluAlanlarBirinciTasSecimiSelect": "1.Taş Seçimi",
    "ZorunluAlanlarIkinciTasSecimiSelect": "2.Taş Seçimi",
    "ZorunluAlanlarUcuncuTasSecimiSelect": "3.Taş Seçimi",
    "ZorunluAlanlarDorduncuTasSecimiSelect": "4.Taş Seçimi",
    "ZorunluAlanlarKostumSuresiSecimiSelect": "Kostüm Süresi Seçiniz",
    "ZorunluAlanlarBilgilendirmeTabIciBasligi": "Bilgilendirmeler",
    "ZorunluAlanlarBilgilendirmeTabIciAciklamasi": "Merhaba, bu dinamik sistem içerisinde efsun,taş,süre gibi dinamik işlemleri gerçekleştirebildiğiniz gibi ayrica bunlardan çok daha fazlasini yapabilirsiniz ve eşsiz eşyalar/itemler üretebilirsiniz.",
    "ZorunluAlanlarSatinAlButtonText": "Satin Al",
    "UyariYetersizEjderhaParasi": "Yetersiz Ejderha Parasi!",
    "SnackBarMesaj1": "Lütfen eşyanin nereye gönderileceğini seçiniz",
    "SnackBarMesaj2": "Lütfen Taş seçiminde birden fazla ayni seçimi yapmayiniz ve boş seçim alanlarina dikkat ediniz. Lütfen Taş seçiminde birden fazla ayni seçimi yapmayiniz ve boş seçim alanlarina dikkat ediniz.",
    "SnackBarMesaj3": "Lütfen Taş seçiminde birden fazla ayni seçimi yapmayiniz ve boş seçim alanlarina dikkat ediniz.",
    "SnackBarMesaj4": "Lütfen Efsun seçiminde birden fazla ayni seçimi yapmayiniz ve boş seçim alanlarina dikkat ediniz.",
    "SnackBarMesaj5": "Lütfen Kostüm Itemi İçin Kostüm Süresi Seçiniz..",
    "SnackBarMesaj6": "Kritik bir hata meydana geldi yönetici ile irtibata geçiniz..",
    "SnackBarMesaj7": "Lütfen Efsun ve Taş seçiminde birden fazla ayni seçimi yapmayiniz ve boş seçim alanlarina dikkat ediniz.",
    "SnackBarMesaj8": "Satin Alma İşlemi Başariyla Gerçekleştirildi Teşekkür Ederiz..",
    "SnackBarMesaj9": "Ejderha parasi alinirken bir hata meydana geldi lütfen tekrar deneyiniz",
    "SnackBarMesaj10": "Ejderha Parasi Boş Bir Değere Sahip Lütfen Tekrar Deneyiniz",
    "SnackBarMesaj11": "Item Gönderilirken Bir Hata Meydana Geldi Yönetici İle İrtibata Geçiniz",
    "SnackBarMesaj12": "Güncellemeler Başariyla Tamamlandi Tebrikler..",
    "SnackBarMesaj13": "Nesne Marketinize",
    "SnackBarMesaj14": "Deponuza",
    "SnackBarMesaj15": "Belirsiz Bir Alana(Yönetici İle İrtibata Geçiniz)",
    "SnackBarMesaj16": "Seçilen İtem",
    "SnackBarMesaj17": "Gönderildi",
    "SnackBarMesaj18": "Bu item stokta tükendi malesef..",
    "SnackBarMesaj19": "NESNE MARKET DEPONUZ FULL DOLU...",
    "SnackBarMesaj20": "İtem Başariyla Eklendi",
    "SnackBarMesaj21": "Belirtilen item seçilen kategoride zaten mevcut. Lütfen başka bir kategori deneyiniz.",
    "SnackBarMesaj22": "Efsun Başariyla Silindi",
    "SnackBarMesaj23": "Silinirken Bir Hata Meydana Geldi!",
    "SnackBarMesaj24": "Efsun Değeri Güncellenemedi!",
    "SnackBarMesaj25": "Efsun Değeri Başariyla Güncellendi",
    "SnackBarMesaj26": "Efsun Başariyla Eklendi",
    "SnackBarMesaj27": "Efsun Eklenemedi.",
    "SnackBarMesaj28": "İşlem Başarisiz Oldu!!",
    "SnackBarMesaj29": "Bu efsunlar zaten var başka efsun deneyiniz.",
    "SnackBarMesaj30": "Belirtilen Kostum Süresini Sildiniz.",
    "SnackBarMesaj31": "Silinirken bir haya meydana geldi!",
    "SnackBarMesaj32": "Kostüm Süresi Başariyla Eklendi",
    "SnackBarMesaj33": "Kostüm Süresi Eklenirken Bir Hata Meydana Geldi!!",
    "SnackBarMesaj34": "Belirtilen Kostüm Süresi Zaten Mevcut",
    "SnackBarMesaj35": "Sunucu Üzerinden Email Gönderildi Yönetici Olmadiğiniz Tespit Edildi!",
    "SnackBarMesaj36": "Bilinmeyen Bir Hata!",
    "SnackBarMesaj37": "Kategori Adi Başariyla Güncellendi",
    "SnackBarMesaj38": "Belirtilen Kategori Güncellenemedi",
    "SnackBarMesaj39": "Böyle bir kategori bulunamadi",
    "SnackBarMesaj40": "Kategorinin ID Değerine Erişilemedi!",
    "SnackBarMesaj41": "Kategori Başariyla Silindi..",
    "SnackBarMesaj42": "Bu Kategoriye Ait İtem Bulunamadi",
    "SnackBarMesaj43": "Kategori Silinemedi!",
    "SnackBarMesaj44": "Eksik Veya Hatali Parametre",
    "SnackBarMesaj45": "Item ve Kategoriler Tamamen Hepsi Silindi.",
    "SnackBarMesaj46": "Lütfen Kategori Adini Giriniz.",
    "SnackBarMesaj47": "Böyle Bir Kategori Adi Zaten Mevcut",
    "SnackBarMesaj48": "Lütfen Kategori Adini Giriniz.",
    "SnackBarMesaj49": "Kategori'si Başariyla Eklendi",
    "SnackBarMesaj50": "Lisans Kodunuz Başariyla Aktive Edilmiştir.",
    "SnackBarMesaj51": "Lisans İçin Gerekli Sunucu Bilgileri Gönderilirken Bir Hata Meydana Geldi",
    "SnackBarMesaj52": "Böyle Bir Lisans Kodu Malesef Yok!",
    "SnackBarMesaj53": "Listeniz'de herhangi bir item eşleşmesi bulunamadi!",
    "SnackBarMesaj54": "Malesef herhangi bir item bulunamadi",
    "SnackBarMesaj55": "Item Adi",
    "SnackBarMesaj56": "Toplam Item Sayisi",
    "SnackBarMesaj57": "Toplam Tutar",
    "SnackBarMesaj58": "Kalan Süresi",
    "SnackBarMesaj59": "Lütfen Bir İtem Seçiniz!!!",
    "SnackBarMesaj60": "İtemi Hesabima Gönder",
    "SnackBarMesaj61": "Lütfen Kupon Kodunuzu Giriniz",
    "SnackBarMesaj62": "KUPONU UYGULA",
    "SnackBarMesaj63": "Day",
    "SnackBarMesaj64": "Nesne Market",
    "SnackBarMesaj65": "Depo",
    "SnackBarMesaj66": "Arama",
    "SnackBarMesaj67": "Giriş Yap",
    "SnackBarMesaj68": "Giriş Yap & Kayit Ol",
    "SnackBarMesaj69": "Üyelik Bilgileriniz",
    "SnackBarMesaj70": "Kullanici Adi",
    "SnackBarMesaj71": "Min 4 Max 30 karakter araliğinda değere sahip olmalidir.",
    "SnackBarMesaj72": "Lütfen email adresini eksiksiz ve doğru bir formatta giriniz.",
    "SnackBarMesaj73": "Email Adresi",
    "SnackBarMesaj74": "Kullanıcı Şifreniz",
    "SnackBarMesaj75": "Lütfen Parolaniz Min 4 Max 30 karakter araliğinda değere sahip olmalidir.",
    "SnackBarMesaj76": "Lütfen Bütün Form Kutularini Eksiksiz Doldurunuz",
    "SnackBarMesaj77": "Lütfen Seçim Kutularini Tamamen Doldurunuz",
    "SnackBarMesaj78": "Örn.25",
    "SnackBarMesaj79": "Efsun Değerinin Limiti",
    "SnackBarMesaj80": "Efsun Ayarlarini Kaydet",
    "SnackBarMesaj81": "İtem Kategorisini Seçiniz",
    "SnackBarMesaj82": "Dikkatli Olunuz.",
    "SnackBarMesaj83": "Efsun Seçiniz",
    "SnackBarMesaj84": "Aşağidaki Efsun sistemi ciddiye alınmadan rastgele dolduruldugunda serveriniz için sorun teşkil eder ve herhangi bir şekilde item kayiplari yüksek efsun oranlari gibi sorunlarla karsılasabilirsiniz doğru yapıcağiniz her işlem nesne market api sistemine uyumlu olaraktan stabil olarak çalışmasini sağlayacaktir..",
    "SnackBarMesaj85": "Efsun Ayarlari",
    "SnackBarMesaj86": "Güncel Efsun Değeri",
    "SnackBarMesaj87": "Efsunu Değiştir/Güncelle",
    "SnackBarMesaj88": "Kapat",
    "SnackBarMesaj89": "Efsun Ayarlarini/Kategorilerini Düzenle",
    "SnackBarMesaj90": "İtem Türünü Seçin",
    "SnackBarMesaj91": "Efsun Düzenle & Sil",
    "SnackBarMesaj92": "Efsun Adi",
    "SnackBarMesaj93": "Max Efsun Değeri",
    "SnackBarMesaj94": "Malesef Herhangi Bir Tür Eşitliği Yok",
    "SnackBarMesaj95": "Kaldir",
    "SnackBarMesaj96": "Düzenle",
    "SnackBarMesaj97": "Lütfen hata alınmış kutulari kontrol ediniz",
    "SnackBarMesaj98": "Lütfen Bütün Seçim Kutularini Doldurunuz.",
    "SnackBarMesaj99": "Lütfen efsun adedini seçiniz.",
    "SnackBarMesaj100": "Lütfen Bütün Seçim Kutularini Doldurunuz.",
    "SnackBarMesaj101": "Bu İtemi Ekle",
    "SnackBarMesaj102": "Eklenebilecek Efsun Adedi",
    "SnackBarMesaj103": "Bu item'e efsun eklenmesine izin veriyormusunuz?",
    "SnackBarMesaj104": "Bu item global olarak süre değerine sahipmi?",
    "SnackBarMesaj105": "Bu item normal olarak +0'dan +9'a kadar arttirilabilir bir item'mi ?",
    "SnackBarMesaj106": "Lütfen sayil değer giriniz. Negatif sayil değer kullanmaktan kaçınınız Örn.(-1,-5,-20) gibi Maximum 99% oranını geçemessiniz",
    "SnackBarMesaj107": "INDIRIM",
    "SnackBarMesaj108": "Bu alana dikkat ediniz.",
    "SnackBarMesaj109": "İtem Fiyati",
    "SnackBarMesaj110": "Kategori Bulunamadi",
    "SnackBarMesaj111": "Kategori Seçiniz",
    "SnackBarMesaj112": "Lütfen İtem Türünü Seçiniz",
    "SnackBarMesaj113": "Listelenen İtemler",
    "SnackBarMesaj114": "Nesne Market'e İtem Ekle",
    "SnackBarMesaj115": "Hayir",
    "SnackBarMesaj116": "Evet",
    "SnackBarMesaj117": "Bu eşyayi Eklemek İstiyormusunuz?",
    "SnackBarMesaj118": "Kategori Adi",
    "SnackBarMesaj119": "Yeni Kategoriyi Ekle",
    "SnackBarMesaj120": "Kategori Ekle",
    "SnackBarMesaj121": "Kategori Adi",
    "SnackBarMesaj122": "Sil",
    "SnackBarMesaj123": "Düzenle",
    "SnackBarMesaj124": "Kategori Adi",
    "SnackBarMesaj125": "Kategori Kaldir",
    "SnackBarMesaj126": "Lütfen bütün alanlari doldurunuz",
    "SnackBarMesaj127": "Kaldir",
    "SnackBarMesaj128": "MALESEF KAYIT YOK",
    "SnackBarMesaj129": "Süre",
    "SnackBarMesaj131": "Biçim",
    "SnackBarMesaj132": "Ek Ücret",
    "SnackBarMesaj133": "Yeni Kostüm Süresini Ekle",
    "SnackBarMesaj134": "Ek Süre Ücreti",
    "SnackBarMesaj135": "Kostüm Süresi Giriniz",
    "SnackBarMesaj136": "Örneğin 1,2,3,4,5",
    "SnackBarMesaj137": "Kostüm Süresi Ekle",
    "SnackBarMesaj138": "HAYIR",
    "SnackBarMesaj139": "EVET",
    "SnackBarMesaj140": "Bu Kategoriyi Silmek İstediğinizden Eminmisiniz ?",
    "SnackBarMesaj141": "Bununla birlikte kategoriye ait bütün item'larda silinecektir.",
    "SnackBarMesaj142": "Bunlari Silmek İstediğinizden Eminmisiniz ?",
    "SnackBarMesaj143": "Kategori Tamamen Boş :)",
    "SnackBarMesaj144": "Kategoride",
    "SnackBarMesaj145": "adet item bulunmaktadir.",
    "SnackBarMesaj146": "Lütfen Kategori Adini Giriniz",
    "SnackBarMesaj147": "Kapat",
    "SnackBarMesaj148": "Kategoriyi Güncelle",
    "SnackBarMesaj149": "Yeni Kategori Adi",
    "SnackBarMesaj150": "Kategori Adini Güncelle",
    "SnackBarMesaj151": "Efsun Düzenle",
    "SnackBarMesaj152": "Efsun Ayarlari",
    "SnackBarMesaj153": "Efsun Sistemi",
    "SnackBarMesaj154": "Süre Ekle",
    "SnackBarMesaj155": "Kostüm Ayarlari",
    "SnackBarMesaj156": "Kategori Kaldir",
    "SnackBarMesaj157": "Kategori Ekle",
    "SnackBarMesaj158": "İtem Ekle",
    "SnackBarMesaj159": "İtem Yönetimi",
    "SnackBarMesaj160": "Menüler",
    "SnackBarMesaj161": "Kategori Ayarlari",
    "SnackBarMesaj162": "Hediye Gönder",
    "SnackBarMesaj163": "Kaç adet item almak istediğinizi belirtiniz. Satin alma esnasında eğer'ki satin almaya çalıştığınız eşyanin indirim gibi bir durumu mevcut ise 2 veya girdiğiniz rakam adedince alinan itemlerde indirime dahil olucaktir..",
    "SnackBarMesaj164": "Hediye Gönderilecek Oyuncunun Karakter Adi",
    "SnackBarMesaj165": "En fazla",
    "SnackBarMesaj166": "adet taş ekleyebilirsiniz",
    "SnackBarMesaj167": "En fazla ",
    "SnackBarMesaj168": " adet efsun ekleyebilirsiniz",
    "SnackBarMesaj169": "Özel İtem Oluştur",
    "SnackBarMesaj170": "Efsun ve Taş Eklemek İstermisiniz",
    "SnackBarMesaj171": "xxxx",
    "SnackBarMesaj172": "xxxx",
    "SnackBarMesaj173": "xxxx",
    "SnackBarMesaj174": "xxxx",
    "SnackBarMesaj175": "xxxx",
    "SnackBarMesaj176": "xxxx",
    "SnackBarMesaj177": "xxxx",
    "SnackBarMesaj178": "xxxx",
    "SnackBarMesaj179": "xxxx",
    "SnackBarMesaj181": "xxxx",
    "SnackBarMesaj182": "xxxx",
    "SnackBarMesaj183": "xxxx",
    "SnackBarMesaj184": "xxxx",
    "SnackBarMesaj185": "xxxx",
    "SnackBarMesaj186": "xxxx",
    "SnackBarMesaj187": "xxxx",
    "SnackBarMesaj188": "xxxx",
    "SnackBarMesaj189": "xxxx",
    "SnackBarMesaj190": "xxxx",

  }],
  EnglishLanguage: [{
    "id": "1",
    "HeaderProfilAdi": "Profil",
    "HeaderProfilNesneDeposuAdi": "Item Shop",
    "HeaderProfilYonetim": "Administration",
    "ZorunluAlanlarModalUstAlanIndirim": "Discount",
    "ZorunluAlanlarModalUstAlanOrjinalFiyat": "Original Price",
    "ZorunluAlanlarModalUstAlanKazanc": "Winnings",
    "ZorunluAlanlarModalUstAlanKostumSureUcreti": "Costum Duration Fee",
    "HeaderEjderhaParasi": "EP",
    "ZorunluAlanlarModalUyariBasligi": "Please be careful when filling the fields below. !!!",
    "ZorunluAlanlarItemNereyeGonderilsinSelect": "Where Item Will Be Sent",
    "ZorunluAlanlarItemAdetBaslikSelect": "Enter the number of items",
    "ZorunluAlanlarEfsunAktifSwitch": "Efsun System Active",
    "ZorunluAlanlarEfsunDeaktifSwitch": "Efsun System Deactive",
    "ZorunluAlanlarTasAktifSwitch": "Stone System Active",
    "ZorunluAlanlarTasDeaktifSwitch": "Stone System Deactive",
    "ZorunluAlanlarDikeyTabMenuBaslik": "Dynamic Features Menu",
    "ZorunluAlanlarDikeyTabEfsunText": "Efsun",
    "ZorunluAlanlarDikeyTabTasText": "Rock",
    "ZorunluAlanlarDikeyTabZamanText": "Time",
    "ZorunluAlanlarDikeyTabBilgiText": "Information",
    "ZorunluAlanlarBirinciEfsunSecimiSelect": "1.Efsun Value",
    "ZorunluAlanlarIkinciEfsunSecimiSelect": "2.Efsun Value",
    "ZorunluAlanlarUcuncuEfsunSecimiSelect": "3.Efsun Value",
    "ZorunluAlanlarDorduncuEfsunSecimiSelect": "4.Efsun Value",
    "ZorunluAlanlarBesinciEfsunSecimiSelect": "5.Efsun Value",
    "ZorunluAlanlarAltinciEfsunSecimiSelect": "6.Efsun Value",
    "ZorunluAlanlarYedinciEfsunSecimiSelect": "7.Efsun Value",
    "ZorunluAlanlarFullOranAlani": "Rate",
    "ZorunluAlanlarBirinciTasSecimiSelect": "1. Stone Selection",
    "ZorunluAlanlarIkinciTasSecimiSelect": "2.Stone Selection",
    "ZorunluAlanlarUcuncuTasSecimiSelect": "3.Stone Selection",
    "ZorunluAlanlarDorduncuTasSecimiSelect": "4.Stone Selection",
    "ZorunluAlanlarKostumSuresiSecimiSelect": "Choose Costume Time",
    "ZorunluAlanlarBilgilendirmeTabIciBasligi": "Notifications",
    "ZorunluAlanlarBilgilendirmeTabIciAciklamasi": "Hello, in this dynamic system, you can perform dynamic operations such as enchantment, stone, time as well as you can do much more than these and produce unique items / items.",
    "ZorunluAlanlarSatinAlButtonText": "Buy",
    "UyariYetersizEjderhaParasi": "Insufficient Dragon Money!",
    "SnackBarMesaj1": "Please select where to send the item",
    "SnackBarMesaj2": "Please do not make more than one same choice in the stone selection and pay attention to the empty selection fields. Please do not make more than one same choice in the stone selection and pay attention to the empty selection fields.",
    "SnackBarMesaj3": "Please do not make more than one same choice in the stone selection and pay attention to the empty selection fields.",
    "SnackBarMesaj4": "Please do not make more than one same choice in Efsun selection and pay attention to empty selection fields.",
    "SnackBarMesaj5": "Please select the costume period for the costume item.",
    "SnackBarMesaj6": "A critical error has occurred. Please contact the administrator.",
    "SnackBarMesaj7": "Please do not select more than one in the selection of Efsun ve Taş and pay attention to the empty selection fields..",
    "SnackBarMesaj8": "Purchase Successfully Completed Thank You ..",
    "SnackBarMesaj9": "An error occurred while receiving dragon money, please try again",
    "SnackBarMesaj10": "Ejderha Parasi Boş Bir Değere Sahip Lütfen Tekrar Deneyiniz",
    "SnackBarMesaj11": "An Error Occurred While Sending The Item. Contact the Administrator",
    "SnackBarMesaj12": "Updates Successfully Completed Congratulations ..",
    "SnackBarMesaj13": "To Your Object Market",
    "SnackBarMesaj14": "your warehouse",
    "SnackBarMesaj15": "An Uncertain Area (Contact the Manager)",
    "SnackBarMesaj16": "Selected Item",
    "SnackBarMesaj17": "Sent",
    "SnackBarMesaj18": "Unfortunately this item is out of stock..",
    "SnackBarMesaj19": "Your object store store is full...",
    "SnackBarMesaj20": "Item Added Successfully",
    "SnackBarMesaj21": "The specified item already exists in the selected category. Please try another category.",
    "SnackBarMesaj22": "Efsun Successfully Deleted",
    "SnackBarMesaj23": "An Error Occurred While Deleting!",
    "SnackBarMesaj24": "Enchant Value Could Not Be Updated!",
    "SnackBarMesaj25": "Enchantment Value Updated Successfully",
    "SnackBarMesaj26": "Efsun Successfully Added",
    "SnackBarMesaj27": "Fauna could not be added.",
    "SnackBarMesaj28": "Transaction Failed !!",
    "SnackBarMesaj29": "These enchantments already exist, try another enchantment.",
    "SnackBarMesaj30": "You have deleted the specified Costume Time.",
    "SnackBarMesaj31": "An error occurred while deleting!",
    "SnackBarMesaj32": "Costume Duration Added Successfully",
    "SnackBarMesaj33": "An Error Occurred While Adding Costume Time !!",
    "SnackBarMesaj34": "The specified costume time is already available",
    "SnackBarMesaj35": "E-mail sent over the server It was detected that you are not an Administrator!",
    "SnackBarMesaj36": "An Unknown Error!",
    "SnackBarMesaj37": "Category Name Updated Successfully",
    "SnackBarMesaj38": "The specified category could not be updated",
    "SnackBarMesaj39": "No such category was found",
    "SnackBarMesaj40": "The ID of the category could not be reached!",
    "SnackBarMesaj41": "Category Successfully Deleted ..",
    "SnackBarMesaj42": "No Items for This Category Are Found",
    "SnackBarMesaj43": "The Category Could Not Be Deleted!",
    "SnackBarMesaj44": "Missing Or Incorrect Parameter",
    "SnackBarMesaj45": "Item and Categories Completely All Deleted.",
    "SnackBarMesaj46": "Please enter the category name.",
    "SnackBarMesaj47": "Such a Category Name Already Exists",
    "SnackBarMesaj48": "Please enter the category name.",
    "SnackBarMesaj49": "Category Added Successfully",
    "SnackBarMesaj50": "Your License Code Has Been Activated Successfully.",
    "SnackBarMesaj51": "An Error Occurred While Sending Server Information Required For License",
    "SnackBarMesaj52": "No Such License Code Sorry!",
    "SnackBarMesaj53": "No item matches were found in your list!",
    "SnackBarMesaj54": "Sorry, no items were found",
    "SnackBarMesaj55": "Item Name",
    "SnackBarMesaj56": "Total Items",
    "SnackBarMesaj57": "Total amount",
    "SnackBarMesaj58": "Remaining Time",
    "SnackBarMesaj59": "Please Select a Item !!!",
    "SnackBarMesaj60": "Send IT to My Account ",
    "SnackBarMesaj61": "Please Enter Your Coupon Code",
    "SnackBarMesaj62": "APPLY COUPON",
    "SnackBarMesaj63": "Day",
    "SnackBarMesaj64": "Item Shop",
    "SnackBarMesaj65": "Store",
    "SnackBarMesaj66": "Search",
    "SnackBarMesaj67": "Login",
    "SnackBarMesaj68": "Login & Register",
    "SnackBarMesaj69": "Your Membership Information",
    "SnackBarMesaj70": "User name",
    "SnackBarMesaj71": "Must have a value of at least 4, at most 30 characters.",
    "SnackBarMesaj72": "Please enter your email address in a complete and correct format.",
    "SnackBarMesaj73": "E mail address",
    "SnackBarMesaj74": "Your User Password",
    "SnackBarMesaj75": "Your Password must have a value in the Min 4 Max 30 character range.",
    "SnackBarMesaj76": "Please Fill All Form Boxes Completely",
    "SnackBarMesaj77": "Please Fill the Selection Boxes Completely",
    "SnackBarMesaj78": "Exmp.25",
    "SnackBarMesaj79": "Limit of Enchantment Value",
    "SnackBarMesaj80": "Save Enchant Settings",
    "SnackBarMesaj81": "Select Item Category",
    "SnackBarMesaj82": "Be Careful.",
    "SnackBarMesaj83": "Choose Efsun",
    "SnackBarMesaj84": "If the following Efsun system is filled randomly without taking it seriously, it will be a problem for your server and in any way, you may encounter problems such as item losses, high enchantment rates.",
    "SnackBarMesaj85": "Enchantment Settings",
    "SnackBarMesaj86": "Current Enchantment Value",
    "SnackBarMesaj87": "Change / Update Your Legend",
    "SnackBarMesaj88": "Close",
    "SnackBarMesaj89": "Edit Enchantment Settings / Categories",
    "SnackBarMesaj90": "Choose Item Type",
    "SnackBarMesaj91": "Edit & Delete Enchantment",
    "SnackBarMesaj92": "Efsun Adi",
    "SnackBarMesaj93": "Max Enchantment Value",
    "SnackBarMesaj94": "Sorry, No Type Equality",
    "SnackBarMesaj95": "Remove",
    "SnackBarMesaj96": "Edit",
    "SnackBarMesaj97": "Please check the boxes with errors",
    "SnackBarMesaj98": "Please Fill All Selection Boxes.",
    "SnackBarMesaj99": "Please select the number of enchantments.",
    "SnackBarMesaj100": "Please Fill All Selection Boxes.",
    "SnackBarMesaj101": "Add This Item",
    "SnackBarMesaj102": "Number of Enchantments That Can Be Added",
    "SnackBarMesaj103": "Do you allow any enchantment to be added to this item?",
    "SnackBarMesaj104": "Does this item have global time value?",
    "SnackBarMesaj105": "Is this item normally an item that can be increased from + 0 to + 9?",
    "SnackBarMesaj106": "Please enter a numerical value. Avoid using a negative number value, for example (- 1, -5, -20).",
    "SnackBarMesaj107": "DISCOUNT",
    "SnackBarMesaj108": "Pay attention to this area.",
    "SnackBarMesaj109": "Item Price",
    "SnackBarMesaj110": "No Category Found",
    "SnackBarMesaj111": "Select Category",
    "SnackBarMesaj112": "Please Select Item Type",
    "SnackBarMesaj113": "Items Listed",
    "SnackBarMesaj114": "Adding Items to Object Market",
    "SnackBarMesaj115": "No",
    "SnackBarMesaj116": "Yeah",
    "SnackBarMesaj117": "Do you want to add this item?",
    "SnackBarMesaj118": "Category Name",
    "SnackBarMesaj119": "Add New Category",
    "SnackBarMesaj120": "Add Category",
    "SnackBarMesaj121": "Category Name",
    "SnackBarMesaj122": "Clear",
    "SnackBarMesaj123": "Edit",
    "SnackBarMesaj124": "Category Name",
    "SnackBarMesaj125": "Remove Category",
    "SnackBarMesaj126": "Please fill all the fields",
    "SnackBarMesaj127": "Remove",
    "SnackBarMesaj128": "NO COST REGISTRATION",
    "SnackBarMesaj129": "Time",
    "SnackBarMesaj131": "Format",
    "SnackBarMesaj132": "Extra pay",
    "SnackBarMesaj133": "Add New Costume Time",
    "SnackBarMesaj134": "Additional Time Fee",
    "SnackBarMesaj135": "Enter Costume Time",
    "SnackBarMesaj136": "For example 1,2,3,4,5",
    "SnackBarMesaj137": "Add Costume Time",
    "SnackBarMesaj138": "NO",
    "SnackBarMesaj139": "YEAH",
    "SnackBarMesaj140": "Are you sure you want to delete this category?",
    "SnackBarMesaj141": "However, all items in the category will be deleted.",
    "SnackBarMesaj142": "Are you sure you want to delete them?",
    "SnackBarMesaj143": "Category Completely Empty :)",
    "SnackBarMesaj144": "Category",
    "SnackBarMesaj145": "There are items.",
    "SnackBarMesaj146": "Please enter the category name",
    "SnackBarMesaj147": "Close",
    "SnackBarMesaj148": "Update Category",
    "SnackBarMesaj149": "New Category Name",
    "SnackBarMesaj150": "Update Category Name",
    "SnackBarMesaj151": "Edit Enchantment",
    "SnackBarMesaj152": "Enchantment Settings",
    "SnackBarMesaj153": "Efsun System",
    "SnackBarMesaj154": "Add Duration",
    "SnackBarMesaj155": "Costume Settings",
    "SnackBarMesaj156": "Remove Category",
    "SnackBarMesaj157": "Add Category",
    "SnackBarMesaj158": "Add Item",
    "SnackBarMesaj159": "Item Management",
    "SnackBarMesaj160": "Menus",
    "SnackBarMesaj161": "Category Settings",
    "SnackBarMesaj162": "Send gift",
    "SnackBarMesaj163": "Please indicate how many items you would like to buy. If the item you are trying to purchase has a status such as a discount during the purchase, 2 or the number of the items you entered will be included in the discount.",
    "SnackBarMesaj164": "xxxx",
    "SnackBarMesaj165": "xxxx",
    "SnackBarMesaj166": "xxxx",
    "SnackBarMesaj167": "xxxx",
    "SnackBarMesaj168": "xxxx",
    "SnackBarMesaj169": "xxxx",
    "SnackBarMesaj170": "xxxx",
  }],
  DilMenusuIzni: false,
  ProfilMenusuIzni: false,
  SecilenDilKodu: null,
  GelenDilVerileri: null,


});
export const mutations = {
  DilleriKaydet(state, payload) {
    state.GelenDiller = payload
  },
  TurkceDiliniKaydet(state, payload) {
    state.TurkishLanguage = payload;
  },
  IngilizceDiliniKaydet(state, payload) {
    state.EnglishLanguage = payload;
  }
};
export const actions = {
  async DilIstekleri({commit, rootState}, payload) {
    await this.$axios.post("index.php?SK=37", {
      ServerID: this.$storage.getLocalStorage("id"),
      SERVER_IP_HOST: this.$storage.getLocalStorage("SERVER_IP_HOST"),
      SERVER_PASSWORD: this.$storage.getLocalStorage("SERVER_PASSWORD"),
      SERVER_ROOT: this.$storage.getLocalStorage("SERVER_ROOT"),
    }).then(res => {
      commit("DilleriKaydet", res.data);
    })
  },
  // async TurkceDiliniGetir({commit}){
  //   await this.$axios.post("index.php?SK=38").then(res=>{
  //     commit("TurkceDiliniKaydet",res.data);
  //   })
  // },
  // async IngilizceDiliniGetir({commit}){
  //   await this.$axios.post("index.php?SK=39").then(res=>{
  //     commit("IngilizceDiliniKaydet",res.data);
  //   })
  // }
};
export const getters = {
  RenderL(state) {
  }
};
